### ISSUE TITLE
Binding lua functions fails

### ISSUE THREAD

**Issue by MikulasVanousek** [LionC/nest.nvim#21] opened 2021-09-26 18:32 UTC
Regular key maps work, but Lua Function Keymaps do not.
This is my binds module:
```
local nest = require('nest')

nest.applyKeymaps {
    { 'gD', lua vim.lsp.buf.declaration }
}
```
Running it produces:
```
E5113: Error while calling lua chunk: vim.lua:64: /home/miki/.config/nvim/lua/miki/binds.lua:4: '}' expected near 'vim'
```

**Comment by LionC** [comment] 2021-09-26 19:17
I think you have a syntax problem in that snippet:

>     { 'gD', lua vim.lsp.buf.declaration }

`lua vim.lsp.buf.declaration` is not a valid lua expression. I think you meant to do

```lua
{ 'gD', vim.lsp.buf.declaration }
```

instead

**Comment by LionC** [comment] 2021-09-26 19:31
I will close this issue as the problem is a syntax problem rather than a problem in nest - if you want to add onto it, feel free to add a comment though :-)

**Closed by LionC** 2021-09-26 19:31 UTC

**Comment by MikulasVanousek** [comment] 2021-09-26 21:03
Thank you for your fast response! 

Now that you say it, I can see it's worng. This is how it is written in your readme, however.

**Comment by LionC** [comment] 2021-09-26 21:33
Oh thanks! I just fixed it :-)
